version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 9443:9443
      - 8000:8000
volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/portainer
