version: "3.8"

services:
  wp_db:
    image: mysql:8.0.19
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - wordpress_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret123$
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=supersecret123
  wp_svc:
    image: wordpress:latest
    ports:
    - 80:80
    restart: always
    environment:
    - WORDPRESS_DB_HOST=wp_db
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=supersecret123$
    - WORDPRESS_DB_NAME=wordpress
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /data/wordpress
      o: bind
